version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  assignees:
    - "bbeesley-bot"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
  groups:
    production-dependencies:
      dependency-type: "production"
    development-dependencies:
      dependency-type: "development"
- package-ecosystem: "github-actions"
  directory: "/"
  assignees:
    - "bbeesley-bot"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
