name: Bullshit
on:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: list
        with:
          script: |
            const { readdir } = require('fs/promises');
            const contents = await readdir('./src');
            console.log({contents});
